### ISSUE TITLE
Add auto deployment through travis CI

### ISSUE THREAD

**Issue by ricardomfmsousa** [ricardomfmsousa/my-vcard#16]
- [Instructions](https://docs.travis-ci.com/user/deployment/pages/)
```yml
before_deploy:
  - ng build --prod --build-optimizer --base-href '/my-resume/'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
```
